language: scala
scala:
  - 2.12.0
  - 2.11.7
  - 2.10.6

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

script:
  - docker-compose up --build -d
  - sleep 30
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts .travis.jvmopts clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
